### ISSUE TITLE
Protobuf version issue

### ISSUE THREAD

**Issue by Usmaniatech** [kotogasy/unity-ml-tennis#3]
![Capture](https://user-images.githubusercontent.com/14370981/59833013-9951e200-935e-11e9-9e3f-5a3ed59fd903.PNG)
How do you solve this issue @kotogasy

**Comment by handria-ntoanina** [comment]
@Usmaniatech , try to create a new environment using anaconda and following the instruction from readme.me under requirement section

**Comment by Usmaniatech** [comment]
I have followed the instructions and I do not find any python folder after installing tensorflow gpu

> Install the dependencies under the folder python/
> cd python
> 	pip install .

What dependencies does this folder installs.

**Comment by handria-ntoanina** [comment]
I have just added the python folder. You can pull the repository and follow the instructions

**Comment by Usmaniatech** [comment]
I have followed the instructions but I am still facing some issues. If I install ml agents setup in our environment then it creates issues with protobuf package as I mentioned earlier and If I dont use mlagents then it gives error for ml agents.
![Capture](https://user-images.githubusercontent.com/14370981/59850737-6de1ee00-9384-11e9-9f56-4bc497fedf0f.PNG)

**Comment by handria-ntoanina** [comment]
@Usmaniatech it is better to create a fresh new environment.
Then, did you follow these:
Perform a minimal install of OpenAI gym
- if using Windows,
-- download swig for windows and add it the PATH of windows
-- install Microsoft Visual C++ Build Tools
- then run these commands
--  pip install gym
--  pip install gym[classic_control]
--  pip install gym[box2d]

If you are using windows and did not install swig and build tools C++, you won't be able to install box2d

**Comment by Usmaniatech** [comment]
When we create build of the environment we have to check the controlbox for the training in unity. If I check it, that needs mlagents. If I dont check it, then it dont load the environment.exe file.
Do we have to install dependencies in mlagents and mlagents-env folder. Because it creates conflicts with unityagents.
So my question is, do we need mlagents for this example to work or it works without that.

**Comment by handria-ntoanina** [comment]
@Usmaniatech , I am just from following the entire requirements steps from scratch. I have added another step to install pytorch. Afterwards, I run the notebook and it ran very well.

**Comment by Usmaniatech** [comment]
Which version of ml-agents you are using ? @kotogasy

**Comment by handria-ntoanina** [comment]
@Usmaniatech just use the one prebuilt environment
